apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 5
  template:
    metadata:
      labels:
        app: client
    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: main
          image: reg.istry.cz/ondrejsika/example-pool-k8s-long-conn--client
          args:
            - sh
            - -c
            - ./client -count 40000 -host server -instance $(hostname)
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
